/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SoliderService } from "../solider.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SoliderCreateInput } from "./SoliderCreateInput";
import { SoliderWhereInput } from "./SoliderWhereInput";
import { SoliderWhereUniqueInput } from "./SoliderWhereUniqueInput";
import { SoliderFindManyArgs } from "./SoliderFindManyArgs";
import { SoliderUpdateInput } from "./SoliderUpdateInput";
import { Solider } from "./Solider";
import { OpinionFindManyArgs } from "../../opinion/base/OpinionFindManyArgs";
import { Opinion } from "../../opinion/base/Opinion";
import { OpinionWhereUniqueInput } from "../../opinion/base/OpinionWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SoliderControllerBase {
  constructor(
    protected readonly service: SoliderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Solider })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: SoliderCreateInput): Promise<Solider> {
    return await this.service.create({
      data: {
        ...data,

        team: data.team
          ? {
              connect: data.team,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Solider] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SoliderFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Solider[]> {
    const args = plainToClass(SoliderFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Solider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SoliderWhereUniqueInput
  ): Promise<Solider | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Solider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SoliderWhereUniqueInput,
    @common.Body() data: SoliderUpdateInput
  ): Promise<Solider | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          team: data.team
            ? {
                connect: data.team,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,

          team: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Solider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SoliderWhereUniqueInput
  ): Promise<Solider | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,

          team: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Opinion",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/opinions")
  @ApiNestedQuery(OpinionFindManyArgs)
  async findManyOpinions(
    @common.Req() request: Request,
    @common.Param() params: SoliderWhereUniqueInput
  ): Promise<Opinion[]> {
    const query = plainToClass(OpinionFindManyArgs, request.query);
    const results = await this.service.findOpinions(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        energy: true,
        id: true,
        positivity: true,
        productivity: true,

        solider: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/opinions")
  async connectOpinions(
    @common.Param() params: SoliderWhereUniqueInput,
    @common.Body() body: OpinionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      opinions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/opinions")
  async updateOpinions(
    @common.Param() params: SoliderWhereUniqueInput,
    @common.Body() body: OpinionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      opinions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Solider",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/opinions")
  async disconnectOpinions(
    @common.Param() params: SoliderWhereUniqueInput,
    @common.Body() body: OpinionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      opinions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
